rename_chem_params = {
    # "Reference":		"",
    "ATCCode_prefix": "ATC_prefix",
    "ATCCode_suffix": "ATC_suffix",
    "Name": "drug_name",
    "IUPACName": "IUPAC_name",
    # "SystematicName":		"",
    "OtherNames": "synonyms",
    # "data page pagename":		"",
    # "Abbreviations":		"",
    "CASNo": "CAS_number",
    "CASNo_Comment": "CAS_supplemental",
    "CASNo_Ref": "CAS_number_Ref",
    # "CASNoOther":		"",
    "PubChem_Comment": "PubChemSubstance",
    "PubChem2_Comment": "PubChemSubstance2",
    "PubChem3_Comment": "PubChemSubstance3",
    "PubChem4_Comment": "PubChemSubstance4",
    "PubChem5_Comment": "PubChemSubstance5",
    # "EINECS":		"",
    # "EC_number":		"",
    # "EC_number_Comment":		"",
    # "UNNumber":		"",
    # "MeSHName":		"",
    "InChI": "StdInChI",
    # "Beilstein":		"",
    # "Gmelin":		"",
    # "3DMet":		"",
    "Formula": "chemical_formula",
    "MolarMass": "molecular_weight",
    # "Appearance":		"",
    "Density": "density",
    "MeltingPt": "melting_point",
    "MeltingPt_notes": "melting_notes",
    "BoilingPt": "boiling_point",
    "BoilingPt_notes": "boiling_notes",
    # "LogP":		"",
    # "VaporPressure":		"",
    # "HenryConstant":		"",
    # "AtmosphericOHRateConstant":		"",
    # "pKa":		"",
    # "pKb":		"",
    "Solubility": "solubility",
    # "SolubleOther":		"",
    # "Solvent":		"",
    # "CrystalStruct":		"",
    # "Coordination":		"",
    # "MolShape":		"",
    # "DeltaGf":		"",
    # "DeltaHc":		"",
    # "DeltaHf":		"",
    # "Entropy":		"",
    # "HeatCapacity":		"",
    "AdminRoutes": "routes_of_administration",
    "Bioavail": "bioavailability",
    "Metabolism": "metabolism",
    "HalfLife": "elimination_half-life",
    "ProteinBound": "protein_bound",
    "Excretion": "excretion",
    # "ShockSens":		"",
    # "FrictionSens":		"",
    # "ExplosiveV":		"",
    # "REFactor":		"",
    # "MainHazards":		"",
    # "NFPA-H":		"",
    # "NFPA-F":		"",
    # "NFPA-I":		"",
    # "NFPA-S":		"",
    # "ExternalSDS":		"",
    # "GHSPictograms":		"",
    # "GHSSignalWord":		"",
    # "HPhrases":		"",
    # "PPhrases":		"",
    # "FlashPt":		"",
    # "Autoignition":		"",
    # "ExploLimits":		"",
    # "LD50":		"",
    # "PEL":		"",
    # "OtherAnions":		"",
    # "OtherCations":		"",
    # "OtherFunction_label":		"",
    # "OtherFunction":		"",
    # "OtherCompounds":		"",
    "ImageFile": "image",
    "ImageSize": "width",
    "ImageAlt": "alt",
    "ImageCaption": "caption",
    "ImageFile1": "image1",
    "ImageSize1": "width1",
    "ImageAlt1": "alt1",
    "ImageCaption1": "caption1",
    "ImageFile2": "image2",
    "ImageSize2": "width2",
    "ImageAlt2": "alt2",
    "ImageCaption2": "caption2",
    "ImageFile3": "image3",
    "ImageSize3": "width3",
    "ImageAlt3": "alt3",
    "ImageCaption3": "caption3",
    "ImageFileL1": "imageL",
    "ImageSizeL1": "widthL",
    "ImageAltL1": "altL",
    "ImageCaptionL1": "captionLR",
    "ImageFileR1": "imageR",
    "ImageSizeR1": "widthR",
    "ImageAltR1": "altR",
    "ImageCaptionR1": "captionLR",
    # "ImageFileL2":		"",
    # "ImageSizeL2":		"",
    # "ImageAltL2":		"",
    # "ImageCaptionL2":		"",
    # "ImageFileR2":		"",
    # "ImageSizeR2":		"",
    # "ImageAltR2":		"",
    # "ImageCaptionR2":		"",
}
# ---
